### ISSUE TITLE
Неработещ плъгин - вероятен проблем с cloudflare? (версия 4.2.0)

### ISSUE THREAD

**Issue by vasilvas99** [zinobg/plugin.video.seirsanduk.r1#4]
Извинявам се за лошото име на това issue, но имах време само частично да разгледам проблема - този последен ъпдейт - 4.2.0 не успява да зареди дори списъка с канали от seir sanduk
Хипотезата ми е, че част от причината е, че `https://www.seir-sanduk.com/` enforce-ва https през клаудфлеър и съответно понякога трябва да се изчакат няколкото секунди преди пренасочване към seir-sanduk.
Подмених base url-a с `http://seirsanduk.online/` и там успешно зареди списъка с канали, но пък не отваря нито един от стриймовете (ще прикача log-ве като имам повече време).

**Comment by vasilvas99** [comment]
Прикачвам log
```
2022-03-25 19:01:28.834 T:18052   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.seirsanduk.r1/stream/https%3A%2F%2Fwww.seir-sanduk.com%2Fbtv-lady-online/BTV+LADY/http%3A%2F%2Fseirsanduk.online%2Fimages%2Ftvlogo%2Fbtv-lady.png/
2022-03-25 19:01:28.834 T:11472   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.seirsanduk.r1/stream/https%3A%2F%2Fwww.seir-sanduk.com%2Fbtv-lady-online/BTV+LADY/http%3A%2F%2Fseirsanduk.online%2Fimages%2Ftvlogo%2Fbtv-lady.png/) failed
2022-03-25 19:01:28.835 T:12852    INFO <general>: initializing python engine.
2022-03-25 19:01:29.102 T:12852    INFO <general>: [xbmcswift2] Request for "/" matches rule for function "index"
2022-03-25 19:01:29.222 T:12852    INFO <general>: CPythonInvoker(13, C:\Users\Vasil\AppData\Roaming\Kodi\addons\plugin.video.seirsanduk.r1\addon.py): script successfully run
2022-03-25 19:01:29.229 T:12852    INFO <general>: Python interpreter stopped
2022-03-25 19:01:31.166 T:1480     INFO <general>: initializing python engine.
2022-03-25 19:01:31.429 T:1480     INFO <general>: [xbmcswift2] Request for "/stream/https%3A%2F%2Fwww.seir-sanduk.com%2Fbulgaria-on-air-online/BULGARIA+ON+AIR/http%3A%2F%2Fseirsanduk.online%2Fimages%2Ftvlogo%2Fbulgaria-on-air.png/" matches rule for function "index_source"
2022-03-25 19:01:31.596 T:1480    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 403: Forbidden
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Vasil\AppData\Roaming\Kodi\addons\plugin.video.seirsanduk.r1\addon.py", line 54, in <module>
                                                       plugin.run()
                                                     File "C:\Users\Vasil\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 338, in run
                                                       items = self._dispatch(self.request.path)
                                                     File "C:\Users\Vasil\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 312, in _dispatch
                                                       listitems = view_func(**items)
                                                     File "C:\Users\Vasil\AppData\Roaming\Kodi\addons\plugin.video.seirsanduk.r1\addon.py", line 38, in index_source
                                                       source=openUrl(url)
                                                     File "C:\Users\Vasil\AppData\Roaming\Kodi\addons\plugin.video.seirsanduk.r1\addon.py", line 48, in openUrl
                                                       response=urllib.request.urlopen(req)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 403: Forbidden
                                                   -->End of Python script error report<--
                                                   
2022-03-25 19:01:31.602 T:1480     INFO <general>: Python interpreter stopped
```
